// <auto-generated />
using System;
using InterviewTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterviewTest.Data.Migrations
{
    [DbContext(typeof(StorageBroker))]
    [Migration("20230206174544_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("InterviewTest.Model.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("47e19e1b-822c-4441-a4b9-70163abbb67a"),
                            Name = "Abul",
                            Value = 1357
                        },
                        new
                        {
                            Id = new Guid("db97b177-ac44-4660-bca2-7577153e7150"),
                            Name = "Adolfo",
                            Value = 1224
                        },
                        new
                        {
                            Id = new Guid("3d8933e0-03f2-4cce-b17c-796e1bd0455c"),
                            Name = "Alexander",
                            Value = 2296
                        },
                        new
                        {
                            Id = new Guid("b97997dc-5233-41b9-ba0c-5c17d6d0b38e"),
                            Name = "Amber",
                            Value = 1145
                        },
                        new
                        {
                            Id = new Guid("bcae1b7f-b6e4-4f50-9c82-65a029ae750e"),
                            Name = "Amy",
                            Value = 4359
                        },
                        new
                        {
                            Id = new Guid("ed7f9b71-6764-47ce-864d-cace6e7d26c9"),
                            Name = "Andy",
                            Value = 1966
                        },
                        new
                        {
                            Id = new Guid("6d61de9c-2faf-4595-9069-194b9ef1220d"),
                            Name = "Anna",
                            Value = 4040
                        },
                        new
                        {
                            Id = new Guid("bc009e00-c659-4fc3-9b3f-1eb50dde12e4"),
                            Name = "Antony",
                            Value = 449
                        },
                        new
                        {
                            Id = new Guid("1b6fb999-236d-4f24-afb7-4b8d3830c054"),
                            Name = "Ashley",
                            Value = 8151
                        },
                        new
                        {
                            Id = new Guid("93da39b3-ad27-4c69-9c53-b780a01dbcb0"),
                            Name = "Borja",
                            Value = 9428
                        },
                        new
                        {
                            Id = new Guid("8b1af87e-805d-4c3c-9b80-fa60bb687122"),
                            Name = "Cecilia",
                            Value = 2136
                        },
                        new
                        {
                            Id = new Guid("9b67d81b-a1e1-4278-84c3-af1201250072"),
                            Name = "Christopher",
                            Value = 9035
                        },
                        new
                        {
                            Id = new Guid("de56e0f5-4492-44e9-9570-cb65c1a3de11"),
                            Name = "Dan",
                            Value = 1475
                        },
                        new
                        {
                            Id = new Guid("1afe428c-341a-4215-b2e8-f35a053e68ca"),
                            Name = "Dario",
                            Value = 284
                        },
                        new
                        {
                            Id = new Guid("b2fe771e-215f-4e92-98dd-d83bd34bcb4c"),
                            Name = "David",
                            Value = 948
                        },
                        new
                        {
                            Id = new Guid("43258789-6cef-4093-abd6-73394c8cdd8d"),
                            Name = "Elike",
                            Value = 1860
                        },
                        new
                        {
                            Id = new Guid("3fcd436e-e782-492a-a61f-ca717d2ff330"),
                            Name = "Ella",
                            Value = 4549
                        },
                        new
                        {
                            Id = new Guid("ab3d1c5e-105f-4c3f-b797-b3d2b810220f"),
                            Name = "Ellie",
                            Value = 5736
                        },
                        new
                        {
                            Id = new Guid("b84d769b-d544-4079-8e16-b467389457dd"),
                            Name = "Elliot",
                            Value = 1020
                        },
                        new
                        {
                            Id = new Guid("fed9971c-70c2-4e30-afa3-5f288a23b14f"),
                            Name = "Emily",
                            Value = 7658
                        },
                        new
                        {
                            Id = new Guid("6d084ceb-82a9-4df9-ab2f-e3739de2cc16"),
                            Name = "Faye",
                            Value = 7399
                        },
                        new
                        {
                            Id = new Guid("dd57c2ae-d145-4b2e-8d4e-53ab9c89d9e8"),
                            Name = "Fern",
                            Value = 1422
                        },
                        new
                        {
                            Id = new Guid("d43d23c3-df06-4bb5-95c4-f2ad389e6830"),
                            Name = "Francisco",
                            Value = 5028
                        },
                        new
                        {
                            Id = new Guid("5373905a-813e-49ac-ba56-9012156f1593"),
                            Name = "Frank",
                            Value = 3281
                        },
                        new
                        {
                            Id = new Guid("01613536-5375-40e8-8141-930fd76beb15"),
                            Name = "Gary",
                            Value = 9190
                        },
                        new
                        {
                            Id = new Guid("e63f9663-8bc0-4f11-a480-b17bf8235630"),
                            Name = "Germaine",
                            Value = 6437
                        },
                        new
                        {
                            Id = new Guid("4fd2c0e3-c0ba-4d02-b2d0-3079f3626a8f"),
                            Name = "Greg",
                            Value = 5929
                        },
                        new
                        {
                            Id = new Guid("ab4b45ef-3ed0-49d5-8f9e-bc3814eee117"),
                            Name = "Harvey",
                            Value = 8471
                        },
                        new
                        {
                            Id = new Guid("8dbbd341-442c-465c-a298-169e7c7b7cdc"),
                            Name = "Helen",
                            Value = 963
                        },
                        new
                        {
                            Id = new Guid("77b90328-0135-4213-b34d-a4508c907ab7"),
                            Name = "Huzairi",
                            Value = 9491
                        },
                        new
                        {
                            Id = new Guid("d2506368-4ffa-430b-a975-c0e9a785e733"),
                            Name = "Izmi",
                            Value = 8324
                        },
                        new
                        {
                            Id = new Guid("b466fbf1-b16d-41fb-8462-87bca8675094"),
                            Name = "James",
                            Value = 6994
                        },
                        new
                        {
                            Id = new Guid("63f5b227-45eb-413c-b6eb-c2407185c5ae"),
                            Name = "Jarek",
                            Value = 6581
                        },
                        new
                        {
                            Id = new Guid("9f638ee8-7721-4e3a-bf4f-f8670dfaccc9"),
                            Name = "Jim",
                            Value = 202
                        },
                        new
                        {
                            Id = new Guid("c702fe18-d4e5-48fe-9196-0871e7697bf2"),
                            Name = "John",
                            Value = 261
                        },
                        new
                        {
                            Id = new Guid("85c5ddc1-191c-4de1-a079-45ee460415b3"),
                            Name = "Jose",
                            Value = 1605
                        },
                        new
                        {
                            Id = new Guid("0da26f0c-421a-40a7-967c-93fbf0f57555"),
                            Name = "Josef",
                            Value = 3714
                        },
                        new
                        {
                            Id = new Guid("a693ca42-2688-4b2f-b752-e0212a281807"),
                            Name = "Karthik",
                            Value = 4828
                        },
                        new
                        {
                            Id = new Guid("e5bc6dbd-18d9-4e04-ba4b-8bac07b28d60"),
                            Name = "Katrin",
                            Value = 5393
                        },
                        new
                        {
                            Id = new Guid("58459587-5215-43ef-a770-77f7417d10ec"),
                            Name = "Lee",
                            Value = 269
                        },
                        new
                        {
                            Id = new Guid("f1d02ef8-9048-4986-a06d-3ebccaf3e461"),
                            Name = "Luke",
                            Value = 5926
                        },
                        new
                        {
                            Id = new Guid("cca207a2-cf5f-4cbe-9ce7-9426b76a8b7a"),
                            Name = "Madiha",
                            Value = 2329
                        },
                        new
                        {
                            Id = new Guid("de97b818-663f-4b74-9d87-acbb87686518"),
                            Name = "Marc",
                            Value = 3651
                        },
                        new
                        {
                            Id = new Guid("e53ccddd-07e5-4119-83c3-01f463b9bab3"),
                            Name = "Marina",
                            Value = 6903
                        },
                        new
                        {
                            Id = new Guid("b82de73d-72d3-4f8c-9273-0a1a6ec59ccb"),
                            Name = "Mark",
                            Value = 3368
                        },
                        new
                        {
                            Id = new Guid("23e7c483-06de-44e1-bd2f-de887c6c664c"),
                            Name = "Marzena",
                            Value = 7515
                        },
                        new
                        {
                            Id = new Guid("65d3c585-0ad3-468b-8837-926afc32afcf"),
                            Name = "Mohamed",
                            Value = 1080
                        },
                        new
                        {
                            Id = new Guid("09f77ea3-bf1c-4df6-b188-0163913d2bea"),
                            Name = "Nichole",
                            Value = 1221
                        },
                        new
                        {
                            Id = new Guid("efb9a9ba-7366-46ea-9d32-716de7511f0d"),
                            Name = "Nikita",
                            Value = 8520
                        },
                        new
                        {
                            Id = new Guid("9394d033-6e76-4894-ad78-2bf8ffa514d0"),
                            Name = "Oliver",
                            Value = 2868
                        },
                        new
                        {
                            Id = new Guid("1e0a1c9c-e8ed-4680-a0ed-66922ccd6b52"),
                            Name = "Patryk",
                            Value = 1418
                        },
                        new
                        {
                            Id = new Guid("0c08428a-94b4-4acf-8bf7-f9a2ed4bdec4"),
                            Name = "Paul",
                            Value = 4332
                        },
                        new
                        {
                            Id = new Guid("bb85a8db-9c3a-47f1-8a89-fa9c45ed1c89"),
                            Name = "Ralph",
                            Value = 1581
                        },
                        new
                        {
                            Id = new Guid("624cabf5-f1e7-43e2-9ec8-d46b7e5a30f1"),
                            Name = "Raymond",
                            Value = 7393
                        },
                        new
                        {
                            Id = new Guid("76f606d8-393b-4cf9-b64f-55c59c91f0f4"),
                            Name = "Roman",
                            Value = 4056
                        },
                        new
                        {
                            Id = new Guid("59efb144-f51e-4c90-8742-361c1940225e"),
                            Name = "Ryan",
                            Value = 252
                        },
                        new
                        {
                            Id = new Guid("7abbb958-fa0a-4a14-9161-2336b94495fa"),
                            Name = "Sara",
                            Value = 2618
                        },
                        new
                        {
                            Id = new Guid("d2038a11-31d2-4124-be8c-5daacb613382"),
                            Name = "Sean",
                            Value = 691
                        },
                        new
                        {
                            Id = new Guid("c2c57ab5-3cdf-4072-99fa-e9e2db295d7f"),
                            Name = "Seb",
                            Value = 5395
                        },
                        new
                        {
                            Id = new Guid("b126d858-8dd1-4560-abaa-bc67edc4b104"),
                            Name = "Sergey",
                            Value = 8282
                        },
                        new
                        {
                            Id = new Guid("27d754f2-e148-4081-b52b-cddc2beb97ca"),
                            Name = "Shaheen",
                            Value = 3721
                        },
                        new
                        {
                            Id = new Guid("036c8215-3747-4bb2-be6a-1c4d38f48e1e"),
                            Name = "Sharni",
                            Value = 7737
                        },
                        new
                        {
                            Id = new Guid("e4f938c5-9975-4481-b5fd-9b63393ad1f4"),
                            Name = "Sinu",
                            Value = 3349
                        },
                        new
                        {
                            Id = new Guid("bcf86dc4-d194-449e-8631-690af3f5175f"),
                            Name = "Stephen",
                            Value = 8105
                        },
                        new
                        {
                            Id = new Guid("12c113d0-1dc3-4934-bbae-ac2a7ae1fe1f"),
                            Name = "Tim",
                            Value = 8386
                        },
                        new
                        {
                            Id = new Guid("67577f37-a12f-4ff7-8410-cf6b740eb04c"),
                            Name = "Tina",
                            Value = 5133
                        },
                        new
                        {
                            Id = new Guid("68a11938-6c30-4193-a624-fd0b5595bc1f"),
                            Name = "Tom",
                            Value = 7553
                        },
                        new
                        {
                            Id = new Guid("8d0c9341-6789-4429-abda-9bbf6054c97f"),
                            Name = "Tony",
                            Value = 4432
                        },
                        new
                        {
                            Id = new Guid("500ee11d-656c-4376-8657-93dd002228bb"),
                            Name = "Tracy",
                            Value = 1771
                        },
                        new
                        {
                            Id = new Guid("7ce1b4ac-9b78-42af-a320-134fa25d13e4"),
                            Name = "Tristan",
                            Value = 2030
                        },
                        new
                        {
                            Id = new Guid("e933f2ce-9b85-4a25-8d1c-2ccee4d6c7b8"),
                            Name = "Victor",
                            Value = 1046
                        },
                        new
                        {
                            Id = new Guid("d83fdd0a-4899-4317-a8c1-de2ca5fb6958"),
                            Name = "Yury",
                            Value = 1854
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
